name: clinical-trial
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pandas=2.2.0
  - numpy=1.26.3
  - scipy=1.10.1
  - scikit-learn=1.4.0
  - matplotlib=3.8.2
  - seaborn=0.13.1
  - tqdm=4.66.1
  - jupyter=1.0.0
  - ipykernel=6.29.0
  - pip=24.0
  - snakemake=8.7.0
#  - pip:
#    - pycox
#    - torchtuples 